### ISSUE TITLE
Problems with PlayerInteractEvent

### ISSUE THREAD

**Issue by 1ntent1on** [MC-Machinations/TreasureMapsPlus#1]
Hello, i started getting error spam when someone uses map.

https://pastebin.com/1usQqsTw

Paper version git-Paper-47 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aea9cdd)
Plugin version 0.3.0

**Comment by Machine-Maker** [comment]
Update to the latest version. You are using 0.1.0 which is only for 1.19.4.

**Comment by Machine-Maker** [comment]
Just to further clarify, you say you are using 0.3.0, but your log shows otherwise. It shows 0.1.0 (and 1.0-SNAPSHOT) before I fixed the plugin version.
![image](https://github.com/MC-Machinations/TreasureMapsPlus/assets/15055071/3dc88d3d-7307-4210-8f4c-f7cce1708bfe)

**Comment by 1ntent1on** [comment]
Yeah, my bad, that was the issue. For some reason the plugin didnt get updated via paper's update folder, was expecting it to be at 0.3.0, but it stayed at 0.1.0.
