### ISSUE TITLE
Please update to 1.20.6

### ISSUE THREAD

**Issue by Leahcimkrob** [MC-Machinations/TreasureMapsPlus#5]
### Expected behavior

Please update to 1.20.6

### Observed/Actual behavior

Please update to 1.20.6

### Steps/models to reproduce

Please update to 1.20.6

### Plugin and Datapack List

CMI, Multiversecore, Fawe ...

### Server Version Info

Please update to 1.20.4

### Plugin Version

0.5.0

**Comment by Machine-Maker** [comment]
https://hangar.papermc.io/Machine_Maker/TreasureMapsPlus/versions/0.6.0
